### PR TITLE
Updates to CSP, XFO, and XXSSP

### PR DESCRIPTION
**Pull request by marumari**
- Show deprecation of XXSSP
- Show slower deprecation of XFO
- More examples for XFO and CSP
- Give useful CSP header for APIs

### CODE REVIEW

**Comment by marumari** [comment]
If I could get a brief r+ on this before merging, that would be great.  Thanks!

**Comment by marumari** [comment]
@claudijd, could you please take a look at this sometime today?  It's not too huge of an update, so shouldn't take that long.  Thanks!

**Comment by claudijd** [comment]
r+

**Comment by marumari** [comment]
Thanks, @claudijd!

**Pull request merged**
