### PR TITLE
Add information about machine accounts w/match and 2FA, sftp logging, and MFA w/ newer OpenSSH

### PR DESCRIPTION
**Pull request by gdestuynder**
need review from @claudijd  @ameihm0912 (this affects the infrasec account though its already setup in a similar way) @bhourigan

### CODE REVIEW

**Comment by gdestuynder** [comment]
Assigned @claudijd for the merge of this so that I'm not too biased one way or another :)

**Comment by jeffbryner** [comment]
r+

**Comment by ameihm0912** [comment]
@gdestuynder r+

**Comment by claudijd** [comment]
@gdestuynder r+ I'll merge and sync in a sec.  Nice job!

**Comment by bhourigan** [comment]
r+

**Comment by claudijd** [comment]
@gdestuynder synced

**Pull request merged**
